add support for base details, such as 'ref', 'repo', 'label' and 'sha'
singer-io/tap-github pull request #109
Opened 2021-04-09 23:09 UTC by felipefrancisco

# Description of change
(write a short description or paste a link to JIRA)

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-04-09 23:09 UTC, cmerrick commented
Hi @felipefrancisco, thanks for your contribution!

In order for us to evaluate and accept your PR, we ask that you [sign a contribution license agreement](https://stitch-cla-enforcer.herokuapp.com/). It's all electronic and will take just minutes.

2021-04-09 23:39 UTC, cmerrick commented
You did it @felipefrancisco!

Thank you for signing the Singer Contribution License Agreement.

2021-04-12 14:08 UTC, dmosorast requested changes

2021-04-12 17:00 UTC, felipefrancisco commented on tap_github/schemas/pull_requests.json
> +      "additionalProperties": false,
Thanks for the feedback, will update 👍🏽

2021-04-12 17:00 UTC, felipefrancisco commented on tap_github/schemas/pull_requests.json
> +              "type": [ "null", "number" ]
Thanks for the feedback, will update 👍🏽

2021-04-14 13:16 UTC, dmosorast approved these changes

2021-04-14 13:16 UTC, merged