Improve rate limiting and retry logic
singer-io/tap-github pull request #142
Opened 2021-11-03 21:35 UTC by loeakaodas

# Description of change
- added backoff retry to `authed_get` method as per [TDL-15621](https://jira.talendforge.org/browse/TDL-15621)
- replaced deprecated `assertEquals` method with `assertEqual` in unit tests

# Manual QA steps
 - rap tap locally
 - ran unit tests
 - ran against `singer-check-tap` and `target-stitch --dry-run`
 - ran tap-tester locally
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-11-04 13:43 UTC, KrisPersonal requested changes
The code should be forked from singer-io: master and not from bytecodeio master. Please do the needful

2021-11-04 13:45 UTC, KrisPersonal commented on tap_github/__init__.py
> +
Please add some comments in the code

2021-11-04 19:51 UTC, loeakaodas commented on tap_github/__init__.py
> +
comments added

2021-11-08 23:08 UTC, loeakaodas commented
Re-submitted in #143 from a branch of master

2021-11-08 23:08 UTC, closed without merging