Re-submitting PR142 (Improve Rate Limit Logic)
singer-io/tap-github pull request #143
Opened 2021-11-08 23:07 UTC by loeakaodas

# Description of change
re-submitting #142 from branch of master

# Manual QA steps
 - see #142 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-11-10 12:59 UTC, kspeer825 requested changes
These unittests should be running in circle as part of the build workflow https://github.com/singer-io/tap-github/blob/01c322f1c2ea1db3e08575218d05ca78f64bc1aa/.circleci/config.yml#L20

2021-11-11 22:50 UTC, loeakaodas commented
> These unittests should be running in circle as part of the build workflow
> 
> https://github.com/singer-io/tap-github/blob/01c322f1c2ea1db3e08575218d05ca78f64bc1aa/.circleci/config.yml#L20

@kspeer825 I had added unit tests to the circle build in #145

2021-11-15 15:50 UTC, luandy64 approved these changes

2021-11-16 22:02 UTC, kspeer825 approved these changes

2021-11-17 23:17 UTC, merged